apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc
  source:
    path: helm-app
    repoURL: https://github.com/surjsingh/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  
  